name: Build and push Docker image

on:
  workflow_call:
    inputs:
      contexts:
        required: true
        type: string
      platforms:
        required: false
        type: string
        default: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    env:
      DOCKER_REGISTRY: ghcr.io/rogerio-planet
      DOCKERFILE: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name and set image tag
        run: |
          BRANCH_NAME=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')
          if [ "$BRANCH_NAME" == "main" ]; then
            IMAGE_TAG="${{ inputs.contexts }}-latest"
          else
            IMAGE_TAG="${{ inputs.contexts }}-${BRANCH_NAME}"
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:            
          install: true
          version: latest
          platforms: ${{ inputs.platforms }}  
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/docker-test:${{ env.IMAGE_TAG }}
          build-args: CONTEXTS=${{ inputs.contexts }}
          no-cache: true
          platforms: ${{ inputs.platforms }}
          provenance: false
          push: true
          
      - name: Clean up disk space
        run: |
          docker image prune -f