name: CI Build and Push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '**'
  
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    permissions:
      id-token: write
      contents: write
      packages: write
      
    with:
      contexts: ${{ matrix.context }}
      platforms: ${{ matrix.platforms }}
    secrets: inherit
    strategy:
      matrix:
        context: ["dev", "integration"]
        platforms: ["linux/amd64", "linux/arm64"]
