name: Cleanup docker images after the merge
on:
  pull_request:
    types:
      - closed

jobs:
  prune-after-merge:
    permissions:
      id-token: write
      contents: write
      packages: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set image name from branch
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
        run: |
          run: |
          echo "BRANCH_NAME=$(echo \"${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}\" \
          | tr '[:upper:]' '[:lower:]' \
          | sed 's/[^a-z0-9]/_/g' \
          | sed 's/^_*\|_*$//g')" >> $GITHUB_ENV

      - name: Prune Docker image from branch merged
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          user: rogerio-planet
          container: docker-test
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: false
          prune-untagged: true
          keep-tags-regexes: |
            dev-latest$|integration-latest$|latest$
          prune-tags-regexes: .*.${{ env.BRANCH_NAME }}$
