name: Prune Docker Images GHCR by parameters

on:
  workflow_dispatch:
    inputs:
      number_of_days:
        description: 'Number of days to keep images'
        type: number
        required: false
        default: 15
      dry_run:
        description: 'Set to true to perform a dry run (no images will be deleted)'
        type: boolean
        required: false
        default: true
      prune_untagged:
        description: 'Set to true to prune untagged images'
        type: boolean
        required: false
        default: false
      keep_tags_regexes:
        description: 'Regex patterns for tags to keep (one per line)'
        type: string
        required: false
        default: '^(dev|integration)-latest$|^(dev|integration)-latest-linux-(amd64|arm64)$'
      prune_tags_regexes:
        description: 'Regex patterns for tags to prune (one per line)'
        type: string
        required: false
        default: '^(integration|dev)-((?!latest).)*$|^(integration|dev)-((?!latest).)*-linux-(amd64|arm64)$'

jobs:
  prune-ghcr:
    permissions:
      id-token: write
      contents: write
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Prune old images except latest tags
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          user: rogerio-planet
          container: docker-test
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.event.inputs.dry_run || 'true' }}
          prune-untagged: ${{ github.event.inputs.prune_untagged || 'false' }}
          keep-younger-than: ${{ github.event.inputs.number_of_days || 15 }}
          keep-tags-regexes: |
            ${{ github.event.inputs.keep_tags_regexes }}
          prune-tags-regexes: |
            ${{ github.event.inputs.prune_tags_regexes }}