name: Schedule clean docker images

on:
  workflow_dispatch:
    inputs:
      number_of_days:
        description: 'Number of days to keep images'
        type: number
        required: false
        default: 15

  schedule:
    - cron: '0 2 * * *'

jobs:
  prune-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Prune old images except env_dev-latest
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          user: rogerio-planet
          container: docker-test
          token: ${{ secrets.READ_PACKAGES }}
          dry-run: false
          prune-untagged: true
          keep-younger-than: ${{ github.event.inputs.number_of_days || 15 }}
          keep-tags-regexes: |
            dev-latest$|integration-latest$
          prune-tags-regexes: |
            ^(integration|dev)-((?!latest).)*$
