name: Cleanup docker images after the merge
on:
  pull_request:
    types:
      - closed

jobs:
  prune-after-merge:
    permissions:
      id-token: write
      contents: write
      packages: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set image name from branch
        run: |
          echo "BRANCH_NAME=$(echo \"${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}\" \
          | tr '[:upper:]' '[:lower:]' \
          | sed 's/[^a-z0-9]/_/g' \
          | sed 's/^_*\|_*$//g')" >> $GITHUB_ENV

      - name: Prune Docker images from merged branch
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          user: rogerio-planet
          container: docker-test
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: false
          prune-untagged: false
          keep-tags-regexes: |
            ^(dev|integration)-latest$
          prune-tags-regexes: |
            ^(dev|integration)-${{ env.BRANCH_NAME }}$|^(dev|integration)-${{ env.BRANCH_NAME }}-linux-(amd64|arm64)$
